seed: 10

dataset:
  train_path: /mnt/parscratch/users/elq20xd/channel_estimation/cc_data/dataset9_N36K4/train_Dataset_dB-25_N36_K4_L6_S9_Setup100_Reliz1000.mat
  valid_path: /mnt/parscratch/users/elq20xd/channel_estimation/cc_data/dataset9_N36K4/valid_Dataset_dB-25_N36_K4_L6_S9_Setup100_Reliz1000.mat

  # train_path: /mnt/parscratch/users/elq20xd/channel_estimation/cc_data/dataset9_N36K4/train_Dataset_dB-25_N36_K4_L4_S10_Setup100_Reliz1000.mat
  # valid_path: /mnt/parscratch/users/elq20xd/channel_estimation/cc_data/dataset9_N36K4/valid_Dataset_dB-25_N36_K4_L4_S10_Setup100_Reliz1000.mat
  with_Vpinv: True

dataloader:
  shuffle: True
  batch_size: 512       # single GPU batch
  num_workers: 1       # number of workers each dataloader

model:
  channel_index: 32

logger:
  path: logger/060225/DiaUNet1D_3l_C32_dB-25_N36K4M4_L6_S9_Set100_reaL1000_L1loss_0502_lr1e2.log