seed: 1234

dataset:
  # train_path: /mnt/fastdata/elq20xd/channel_estimation/dataset11/train_Dataset_dB-25_N36_K4_L4_S9_Setup200_Reliz500.mat
  # valid_path: /mnt/fastdata/elq20xd/channel_estimation/dataset11/valid_Dataset_dB-25_N36_K4_L4_S9_Setup20_Reliz500.mat

  train_path: /mnt/parscratch/users/elq20xd/channel_estimation/cc_data/fixed_UEs_15GHz/train_Dataset_dB-15_N36_K4_L4_S9_Setup200_Reliz1000Ran1.mat
  valid_path: /mnt/parscratch/users/elq20xd/channel_estimation/cc_data/fixed_UEs_15GHz/valid_Dataset_dB-15_N36_K4_L4_S9_Setup20_Reliz1000Ran1.mat
  
  norm_H: True

dataloader:
  shuffle: True
  batch_size: 128       # single GPU batch
  num_workers: 1       # number of workers each dataloader

# model:
#   name: DnCNN_MultiBlock_ds
#   params:
#     block: 3
#     depth: 18
#     image_channels: 2
#     filters: 64
#     use_bnorm: true

# model:
#   name: DiaUNet1D
#   params:
#     in_channels: 2
#     out_channels: 2
#     base_channels: 32
#     num_layers: 1
#     withVpinv: False

model:
  name: AttentionCE
  params:
    in_channels: 2
    feature_dim: 256


trainer:
  optimizer: 
    name: "Adam"
    params:
      lr: 0.001
      weight_decay: 0.001

  lr_scheduler:
    name: ReduceLROnPlateau
    params:
      factor: 0.1
      patience: 10
      min_lr: 1e-6
      threshold: 0.001
      threshold_mode: "abs"

  epoch_num: 100

  loss: L1Loss  #L1Loss  MSELoss SmoothL1Loss
  # beta: 0.053

  is_finetune: Flase
  path: None
