seed: 10

dataset:
  # train_path: /mnt/fastdata/elq20xd/channel_estimation/dataset11/train_Dataset_dB-25_N36_K4_L4_S9_Setup200_Reliz500.mat
  # valid_path: /mnt/fastdata/elq20xd/channel_estimation/dataset11/valid_Dataset_dB-25_N36_K4_L4_S9_Setup20_Reliz500.mat

  # train_path: /mnt/parscratch/users/elq20xd/channel_estimation/cc_data/dataset10_N36K4_3types/train_Dataset_dB-15_N36_K4_L4_S9_Setup100_Reliz1000.mat
  # valid_path: /mnt/parscratch/users/elq20xd/channel_estimation/cc_data/dataset10_N36K4_3types/test_Dataset_dB-15_N36_K4_L4_S9_Setup10_Reliz1000.mat
  train_path: /mnt/parscratch/users/elq20xd/channel_estimation/cc_data/dataset13_N36K4M4/train_Dataset_dB-15_N36_K4_L5_S9_Setup200_Reliz1000.mat
  valid_path: /mnt/parscratch/users/elq20xd/channel_estimation/cc_data/dataset13_N36K4M4/test_Dataset_dB-15_N36_K4_L5_S9_Setup20_Reliz1000.mat

  with_Vpinv: True

dataloader:
  shuffle: True
  batch_size: 512       # single GPU batch
  num_workers: 1       # number of workers each dataloader

# model:
#   name: DnCNN_MultiBlock_ds
#   params:
#     block: 3
#     depth: 18
#     image_channels: 2
#     filters: 64
#     use_bnorm: true

model:
  name: DiaUNet1D
  params:
    in_channels: 2
    out_channels: 2
    base_channels: 16
    num_layers: 3

# model:
#   name: LeNet
#   params:
#     in_channels: 2
#     out_channels: 2
#     hidden_dim: 512
#     num_fc_layers: 3

trainer:
  optimizer: 
    name: "Adam"
    params:
      lr: 0.001
      weight_decay: 0.001

    # name: "SGD"
    # params:
    #   lr: 0.01
    #   momentum: 0.9
    #   weight_decay: 0.001

  lr_scheduler:
    name: StepLR
    params:
      step_size: 60
      gamma: 0.1

  epoch_num: 240

  loss: L1Loss  #L1Loss  MSELoss SmoothL1Loss
