seed: 10

dataset:
  train_path: /mnt/fastdata/elq20xd/channel_estimation/dataset11/train_Dataset_dB-25_N36_K4_L4_S9_Setup200_Reliz500.mat
  valid_path: /mnt/fastdata/elq20xd/channel_estimation/dataset11/valid_Dataset_dB-25_N36_K4_L4_S9_Setup20_Reliz500.mat

  # train_path: /mnt/parscratch/users/elq20xd/channel_estimation/cc_data/dataset9_N36K4/train_Dataset_dB-25_N36_K4_L4_S10_Setup100_Reliz1000.mat
  # valid_path: /mnt/parscratch/users/elq20xd/channel_estimation/cc_data/dataset9_N36K4/valid_Dataset_dB-25_N36_K4_L4_S10_Setup100_Reliz1000.mat
  with_Vpinv: True

dataloader:
  shuffle: True
  batch_size: 512       # single GPU batch
  num_workers: 1       # number of workers each dataloader

model:
  channel_index: 32
  num_layers: 3

logger:
  path: logger/120225/DnCNNMultiBlock_B3Depth16_dB-15_N36K4M4_L4_S9_Set100_reaL1000_L1loss_1202_lr1e3.log